<template>
  <div
    class="w-screen h-screen overflow-hidden flex justify-center items-center bg-neutral fixed top-0 z-50"
  >
    <div class="loadingio-spinner-dual-ring-ejy6pu25lrw">
      <div class="ldio-32g5goqgllz">
        <div></div>
        <div><div></div></div>
      </div>
    </div>
  </div>
</template>

<script>
export default {}
</script>

<style scoped>
@keyframes ldio-32g5goqgllz {
  0% {
    transform: rotate(0);
  }
  100% {
    transform: rotate(360deg);
  }
}
.ldio-32g5goqgllz div {
  box-sizing: border-box !important;
}
.ldio-32g5goqgllz > div {
  position: absolute;
  width: 149.04px;
  height: 149.04px;
  top: 28.979999999999997px;
  left: 28.979999999999997px;
  border-radius: 50%;
  border: 12.419999999999998px solid #000;
  border-color: #55c89d transparent #55c89d transparent;
  animation: ldio-32g5goqgllz 1.408450704225352s linear infinite;
}
.ldio-32g5goqgllz > div:nth-child(2) {
  border-color: transparent;
}
.ldio-32g5goqgllz > div:nth-child(2) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-32g5goqgllz > div:nth-child(2) div:before,
.ldio-32g5goqgllz > div:nth-child(2) div:after {
  content: '';
  display: block;
  position: absolute;
  width: 12.419999999999998px;
  height: 12.419999999999998px;
  top: -12.419999999999998px;
  left: 55.88999999999999px;
  background: #55c89d;
  border-radius: 50%;
  box-shadow: 0 136.61999999999998px 0 0 #55c89d;
}
.ldio-32g5goqgllz > div:nth-child(2) div:after {
  left: -12.419999999999998px;
  top: 55.88999999999999px;
  box-shadow: 136.61999999999998px 0 0 0 #55c89d;
}
.loadingio-spinner-dual-ring-ejy6pu25lrw {
  width: 207px;
  height: 207px;
  display: inline-block;
  overflow: hidden;
  background: #000000;
}
.ldio-32g5goqgllz {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-32g5goqgllz div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
